railstutorial: "https://www.railstutorial.org/"
learnenough: "https://www.learnenough.com/"
railstutorial_book: "https://www.railstutorial.org/book"
railstutorial_help: "https://www.railstutorial.org/help"
screencasts: "https://screencasts.railstutorial.org/"
author: "https://github.com/chienpt98"
news: "https://news.railstutorial.org/"
contact: "https://github.com/chienpt98"
static_pages:
    home:
      image_size: 200px
    links:
      rails_tutorial:
        home_page: https://www.railstutorial.org/
        help_page: https://www.railstutorial.org/help
        book_page: https://www.railstutorial.org/book
        screencasts_page: https://screencasts.railstutorial.org/
        contact_page: https://www.railstutorial.org/contact
        new_page: https://news.railstutorial.org/
        author: https://www.michaelhartl.com/
validations:
  name:
    max_length: 50
  email:
    max_length: 255
    regex: !ruby/regexp '/\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i'
  password:
    min_length: 6
  content:
    max_length: 140
links:
  gravartar: https://secure.gravatar.com/avatar/

sessions:
  create:
    select_box: 1
gravartar:
  size_default: 80
  size_list: 50
  options_link: '?s=%{size}'
password_reset:
  expired_time: 2
files:
  image_type: /%w(image/jpeg image/gif image/png)/
  valid_input: image/jpeg,image/gif,image/png
  pic_resize: 500
  pic_size: 5
  change_digit: 1048576
